# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CorporalMassView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from URL import url
import requests

class Ui_CorporalMassView(object):
    def setupUi(self, CorporalMassView):
        CorporalMassView.setObjectName("CorporalMassView")
        CorporalMassView.resize(770, 600)
        CorporalMassView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(CorporalMassView)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 160, 181, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 160, 211, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(330, 260, 131, 31))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 192, 114);color: rgb(0, 0, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.getData)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 200, 191, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 200, 211, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(260, 350, 101, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 350, 151, 22))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")

        CorporalMassView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CorporalMassView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 26))
        self.menubar.setObjectName("menubar")

        CorporalMassView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CorporalMassView)
        self.statusbar.setObjectName("statusbar")
        CorporalMassView.setStatusBar(self.statusbar)

        self.retranslateUi(CorporalMassView)
        QtCore.QMetaObject.connectSlotsByName(CorporalMassView)

    def retranslateUi(self, CorporalMassView):
        _translate = QtCore.QCoreApplication.translate
        CorporalMassView.setWindowTitle(_translate("CorporalMassView", "CorporalMassView"))
        self.label.setText(_translate("CorporalMassView", "Ingrese la densidad del cuerpo"))
        self.label_2.setText(_translate("CorporalMassView", "Predecir la cantidad de masa corporal"))
        self.pushButton_12.setText(_translate("CorporalMassView", "Predecir"))
        self.label_3.setText(_translate("CorporalMassView", "Ingrese la medidad del abdomen"))
        self.label_5.setText(_translate("CorporalMassView", "Masa Corporal ~"))

    def getData(self):

        response = requests.get(url + "/modelMasaCorporal?Density=" + self.lineEdit.text() + "&Abdomen=" + self.lineEdit_2.text())
        info = response.json()

        self.lineEdit_3.setText(str(info["Result"]["0"]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CorporalMassView = QtWidgets.QMainWindow()
    ui = Ui_CorporalMassView()
    ui.setupUi(CorporalMassView)
    CorporalMassView.show()
    sys.exit(app.exec_())

def getData(self):

        url = "http://495f-34-125-46-48.ngrok.io"

        Sex = ""
        if self.Sex.currentText() == "Male":
            Sex = "0"
        else:
            Sex = "1"

        response = requests.get(url + "/modelCirrosis?N_Days=" + self.NDays.text() + "&Status=" + self.Status.text() + "&Drug=" + 
        self.Drug.text() + "&Age=" + self.Age.text() + "&Sex=" + Sex + "&Ascites=" + self.Ascites.text() + "&Hepatomegaly=" + 
        self.Hepatomegaly.text() + "&Spiders=" + self.Spiders.text() + "&Edema=" + self.Edema.text() + "&Bilirubin=" + self.Bilirubin.text()
         + "&Cholesterol=" + self.Cholesterol.text() + "&Albumin=" + self.Albumin.text() + "&Copper=" + self.Copper.text() + "&Alk_Phos=" + 
         self.AlkPhos.text() + "&SGOT=" + self.SGOT.text() + "&Tryglicerides=" + self.Tryglicerides.text() + "&Platelets=" + 
         self.Platelets.text() + "&Prothrombin=" + self.Prothrombin.text())
        
        info = response.json()

        self.Res.setText(str(info["Result"]["0"]))