# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HepatitisView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from URL import url
import requests


class Ui_HepatitisView(object):
    def setupUi(self, HepatitisView):
        HepatitisView.setObjectName("HepatitisView")
        HepatitisView.resize(774, 600)
        HepatitisView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(HepatitisView)
        self.centralwidget.setObjectName("centralwidget")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 30, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.Age = QtWidgets.QLineEdit(self.centralwidget)
        self.Age.setGeometry(QtCore.QRect(350, 90, 191, 22))
        self.Age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Age.setObjectName("Age")

        self.ALP = QtWidgets.QLineEdit(self.centralwidget)
        self.ALP.setGeometry(QtCore.QRect(350, 180, 191, 22))
        self.ALP.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ALP.setObjectName("ALP")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 390, 121, 20))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")

        self.BIL = QtWidgets.QLineEdit(self.centralwidget)
        self.BIL.setGeometry(QtCore.QRect(350, 270, 191, 22))
        self.BIL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BIL.setObjectName("BIL")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 240, 121, 20))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")

        self.AST = QtWidgets.QLineEdit(self.centralwidget)
        self.AST.setGeometry(QtCore.QRect(350, 240, 191, 22))
        self.AST.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.AST.setObjectName("AST")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 120, 121, 20))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")

        self.ALT = QtWidgets.QLineEdit(self.centralwidget)
        self.ALT.setGeometry(QtCore.QRect(350, 210, 191, 22))
        self.ALT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ALT.setObjectName("ALT")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 210, 121, 20))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(220, 360, 121, 20))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 150, 121, 20))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 300, 121, 20))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")

        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(320, 460, 131, 31))
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 192, 114);color: rgb(0, 0, 0);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.clicked.connect(self.getData)

        self.CHE = QtWidgets.QLineEdit(self.centralwidget)
        self.CHE.setGeometry(QtCore.QRect(350, 300, 191, 22))
        self.CHE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CHE.setObjectName("CHE")

        self.CHOL = QtWidgets.QLineEdit(self.centralwidget)
        self.CHOL.setGeometry(QtCore.QRect(350, 330, 191, 22))
        self.CHOL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CHOL.setObjectName("CHOL")

        self.GGT = QtWidgets.QLineEdit(self.centralwidget)
        self.GGT.setGeometry(QtCore.QRect(350, 390, 191, 22))
        self.GGT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.GGT.setObjectName("GGT")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 180, 121, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(220, 420, 121, 20))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(220, 270, 121, 20))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")

        self.CREA = QtWidgets.QLineEdit(self.centralwidget)
        self.CREA.setGeometry(QtCore.QRect(350, 360, 191, 22))
        self.CREA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CREA.setObjectName("CREA")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(220, 330, 121, 20))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")

        self.ALB = QtWidgets.QLineEdit(self.centralwidget)
        self.ALB.setGeometry(QtCore.QRect(350, 150, 191, 22))
        self.ALB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ALB.setObjectName("ALB")

        self.PROT = QtWidgets.QLineEdit(self.centralwidget)
        self.PROT.setGeometry(QtCore.QRect(350, 420, 191, 22))
        self.PROT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PROT.setObjectName("PROT")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 90, 121, 20))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(260, 510, 61, 20))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")

        self.Res = QtWidgets.QLineEdit(self.centralwidget)
        self.Res.setGeometry(QtCore.QRect(320, 510, 191, 22))
        self.Res.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Res.setReadOnly(True)
        self.Res.setObjectName("Res")

        self.Sex = QtWidgets.QComboBox(self.centralwidget)
        self.Sex.setGeometry(QtCore.QRect(350, 120, 73, 22))
        self.Sex.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Sex.setObjectName("Sex")
        self.Sex.addItem("")
        self.Sex.addItem("")

        HepatitisView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HepatitisView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 26))
        self.menubar.setObjectName("menubar")

        HepatitisView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HepatitisView)
        self.statusbar.setObjectName("statusbar")
        HepatitisView.setStatusBar(self.statusbar)

        self.retranslateUi(HepatitisView)
        QtCore.QMetaObject.connectSlotsByName(HepatitisView)

    def retranslateUi(self, HepatitisView):
        _translate = QtCore.QCoreApplication.translate
        HepatitisView.setWindowTitle(_translate("HepatitisView", "HepatitisView"))
        self.label_2.setText(_translate("HepatitisView", "Classify the type of hepatitis"))
        self.label_12.setText(_translate("HepatitisView", "Enter the GGT"))
        self.label_6.setText(_translate("HepatitisView", "Enter the AST"))
        self.label_3.setText(_translate("HepatitisView", "Select the Sex"))
        self.label_7.setText(_translate("HepatitisView", "Enter the ALT"))
        self.label_8.setText(_translate("HepatitisView", "Enter the CREA"))
        self.label_4.setText(_translate("HepatitisView", "Enter the ALB"))
        self.label_10.setText(_translate("HepatitisView", "Enter the CHE"))
        self.pushButton_13.setText(_translate("HepatitisView", "Classify"))
        self.label_5.setText(_translate("HepatitisView", "Enter the ALP"))
        self.label_13.setText(_translate("HepatitisView", "Enter the PROT"))
        self.label_11.setText(_translate("HepatitisView", "Enter the BIL"))
        self.label_9.setText(_translate("HepatitisView", "Enter the CHOL"))
        self.label.setText(_translate("HepatitisView", "Enter the Age"))
        self.label_14.setText(_translate("HepatitisView", "Type"))
        self.Sex.setItemText(0, _translate("HepatitisView", "Male"))
        self.Sex.setItemText(1, _translate("HepatitisView", "Female"))

    def getData(self):

        Sex = ""
        if self.Sex.currentText() == "Male":
            Sex = "0"
        else:
            Sex = "1"

        response = requests.get(url + "/modelHepatitis?Age=" + self.Age.text() + "&Sex=" + Sex + "&ALB=" + 
        self.ALB.text() + "&ALP=" + self.ALP.text() + "&ALT=" + self.ALT.text() + "&AST=" + self.AST.text() + "&BIL=" + self.BIL.text() 
        + "&CHE=" + self.CHE.text() + "&CHOL=" + self.CHOL.text() + "&CREA=" + self.CREA.text() + "&GGT=" + self.GGT.text() + "&PROT=" + 
        self.PROT.text())
        
        info = response.json()

        self.Res.setText(str(info["Result"]["0"]))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HepatitisView = QtWidgets.QMainWindow()
    ui = Ui_HepatitisView()
    ui.setupUi(HepatitisView)
    HepatitisView.show()
    sys.exit(app.exec_())
