# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HouseView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from URL import url
import requests


class Ui_HouseView(object):
    def setupUi(self, HouseView):
        HouseView.setObjectName("HouseView")
        HouseView.resize(774, 600)
        HouseView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(HouseView)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 70, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(208, 180, 171, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 180, 221, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(350, 230, 131, 31))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 192, 114);color: rgb(0, 0, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.getData)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 320, 91, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 320, 145, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        HouseView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HouseView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 26))
        self.menubar.setObjectName("menubar")
        HouseView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HouseView)
        self.statusbar.setObjectName("statusbar")
        HouseView.setStatusBar(self.statusbar)

        self.retranslateUi(HouseView)
        QtCore.QMetaObject.connectSlotsByName(HouseView)

    def retranslateUi(self, HouseView):
        _translate = QtCore.QCoreApplication.translate
        HouseView.setWindowTitle(_translate("HouseView", "MainWindow"))
        self.label_2.setText(_translate("HouseView", "Predecir precio de una casa"))
        self.label.setText(_translate("HouseView", "Metros cuadrados de la casa"))
        self.pushButton_12.setText(_translate("HouseView", "Predecir"))
        self.label_5.setText(_translate("HouseView", "Precio"))

    def getData(self):

        response = requests.get(url + "/modelCasa?sqft_living=" + self.lineEdit.text())
        info = response.json()

        self.lineEdit_2.setText(str(info["Result"]["0"]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HouseView = QtWidgets.QMainWindow()
    ui = Ui_HouseView()
    ui.setupUi(HouseView)
    HouseView.show()
    sys.exit(app.exec_())
