# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LondresView.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from URL import url
import requests


class Ui_LondresView(object):
    def setupUi(self, LondresView):
        LondresView.setObjectName("LondresView")
        LondresView.resize(776, 600)
        LondresView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(LondresView)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 611, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(340, 240, 131, 31))
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 192, 114);color: rgb(0, 0, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.clicked.connect(self.getData)

        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(500, 160, 73, 22))
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setFrame(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 160, 16, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(340, 160, 51, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 160, 111, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 160, 16, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(420, 160, 51, 22))
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setFrame(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 360, 151, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 360, 91, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 320, 91, 16))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 320, 151, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")

        LondresView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LondresView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 26))
        self.menubar.setObjectName("menubar")

        LondresView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LondresView)
        self.statusbar.setObjectName("statusbar")
        LondresView.setStatusBar(self.statusbar)

        self.retranslateUi(LondresView)
        QtCore.QMetaObject.connectSlotsByName(LondresView)

    def retranslateUi(self, LondresView):
        _translate = QtCore.QCoreApplication.translate
        LondresView.setWindowTitle(_translate("LondresView", "MainWindow"))
        self.label_2.setText(_translate("LondresView", "Predecir la cantidad de crimen en Londres"))
        self.pushButton_12.setText(_translate("LondresView", "Predecir"))
        self.comboBox_4.setItemText(0, _translate("LondresView", "2023"))
        self.comboBox_4.setItemText(1, _translate("LondresView", "2024"))
        self.comboBox_4.setItemText(2, _translate("LondresView", "2025"))
        self.comboBox_4.setItemText(3, _translate("LondresView", "2026"))
        self.comboBox_4.setItemText(4, _translate("LondresView", "2027"))
        self.comboBox_4.setItemText(5, _translate("LondresView", "2028"))
        self.comboBox_4.setItemText(6, _translate("LondresView", "2029"))
        self.comboBox_4.setItemText(7, _translate("LondresView", "2030"))
        self.label_3.setText(_translate("LondresView", "/"))
        self.comboBox.setItemText(0, _translate("LondresView", "01"))
        self.label.setText(_translate("LondresView", "Ingrese una fecha"))
        self.label_4.setText(_translate("LondresView", "/"))
        self.comboBox_5.setItemText(0, _translate("LondresView", "01"))
        self.comboBox_5.setItemText(1, _translate("LondresView", "02"))
        self.comboBox_5.setItemText(2, _translate("LondresView", "03"))
        self.comboBox_5.setItemText(3, _translate("LondresView", "04"))
        self.comboBox_5.setItemText(4, _translate("LondresView", "05"))
        self.comboBox_5.setItemText(5, _translate("LondresView", "06"))
        self.comboBox_5.setItemText(6, _translate("LondresView", "07"))
        self.comboBox_5.setItemText(7, _translate("LondresView", "08"))
        self.comboBox_5.setItemText(8, _translate("LondresView", "09"))
        self.comboBox_5.setItemText(9, _translate("LondresView", "10"))
        self.comboBox_5.setItemText(10, _translate("LondresView", "11"))
        self.comboBox_5.setItemText(11, _translate("LondresView", "12"))
        self.label_6.setText(_translate("LondresView", "Valor Maximo"))
        self.label_5.setText(_translate("LondresView", "Valor Minimo"))

    def getData(self):

        date = self.comboBox_4.currentText() + "-" + self.comboBox_5.currentText() + "-" + self.comboBox.currentText()
        
        response = requests.get(url + "/modelCrimenes?fecha=" + date)
        info = response.json()

        self.lineEdit.setText(str(info[date+"T00:00:00.000Z"]["lower value"]))
        self.lineEdit_2.setText(str(info[date+"T00:00:00.000Z"]["upper value"]))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LondresView = QtWidgets.QMainWindow()
    ui = Ui_LondresView()
    ui.setupUi(LondresView)
    LondresView.show()
    sys.exit(app.exec_())
